LOCAL fileName IS "0:PID Settings.csv".
LOG "PID,kP,kI,kD" TO fileName.
LOG "Pitch," + STEERINGMANAGER:PITCHPID:KP + "," + STEERINGMANAGER:PITCHPID:KI + "," + STEERINGMANAGER:PITCHPID:KD TO fileName.
LOG "Yaw," + STEERINGMANAGER:YAWPID:KP + "," + STEERINGMANAGER:YAWPID:KI + "," + STEERINGMANAGER:YAWPID:KD TO fileName.
LOG "Roll," + STEERINGMANAGER:ROLLPID:KP + "," + STEERINGMANAGER:ROLLPID:KI + "," + STEERINGMANAGER:ROLLPID:KD TO fileName.
